# Generated by Django 2.1.7 on 2019-03-12 07:44

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190311_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='post_content',
            field=markdownx.models.MarkdownxField(max_length=500),
        ),
    ]
