# Generated by Django 2.1.7 on 2019-03-13 20:14

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190312_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogposts',
            old_name='dateposted',
            new_name='date_posted',
        ),
        migrations.AddField(
            model_name='blogposts',
            name='author',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='post_content',
            field=markdownx.models.MarkdownxField(default='NULL', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='title',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
