# Generated by Django 2.1.7 on 2019-03-15 08:01

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190313_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='post_content',
            field=markdownx.models.MarkdownxField(max_length=99999),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
