# Generated by Django 2.1.7 on 2019-02-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileHandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='static/users/')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
